### ISSUE TITLE
CMake cannot find fortran after restoring from the cache

### ISSUE THREAD

**Issue by sanguinariojoe** [modflowpy/install-intelfortran-action#10]
See https://github.com/sanguinariojoe/MoorDyn/actions/runs/3302454942/jobs/5449849001

It works just fine when installing from scratch (https://github.com/sanguinariojoe/MoorDyn/actions/runs/3273534330/jobs/5385863752)

**Comment by sanguinariojoe** [comment]
I ran it again printing the CMake logs afterwards:

https://github.com/sanguinariojoe/MoorDyn/actions/runs/3302867330/jobs/5450148949

**Comment by wpbonelli** [comment]
@sanguinariojoe I verified this [still occurs](https://github.com/w-bonelli/MoorDyn/actions/runs/3307346880/jobs/5458910370#step:10:31) despite `ifort.exe` being on the PATH and `FC=ifort` set. I also tried setting the `-DCMAKE_Fortran_COMPILER=ifort` option (and `CMAKE_FORTRAN_COMPILER` etc to check for case sensitivity) with no luck.

I wonder if using a different CMake version might make any difference. There seem to be [similar](https://stackoverflow.com/questions/59257984/ifort-compiler-not-found-by-cmake) [issues](https://discourse.cmake.org/t/how-to-set-up-compilation-with-intel-fortran-compiler-on-windows-correctly/532) [reported](https://community.intel.com/t5/Intel-Fortran-Compiler/CMake-fails-at-the-Fortran-compiler-ABI-info-detection-with/m-p/1319541) elsewhere with CMake detecting `ifort`. Since MODFLOW does not use CMake this is not at the top of my queue but I will let you know if I make any further headway. Apologies for the trouble.

**Comment by sanguinariojoe** [comment]
Just for the record, I printed all the env vars with and without cache, and everything looks the same. I will further investigate...

**Comment by wpbonelli** [comment]
@sanguinariojoe

Maybe some tentative progress here. Adding some options [allows the CMAKE setup step to pass](https://github.com/w-bonelli/MoorDyn/actions/runs/3430563754/jobs/5717687754) even after cache restore:

- `-DCMAKE_Fortran_COMPILER="C:/Program Files (x86)/Intel/oneAPI/compiler/2022.2.0/windows/bin/intel64/ifort.exe"`: tell CMAKE exactly where `ifort` is (not found otherwise, even though it's on the path)
- `-G "MinGW Makefiles" `: use the [MinGW makefile generator](https://cmake.org/cmake/help/latest/generator/MinGW%20Makefiles.html) (I think this defaults to [visual studio](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html) on Windows, which the docs say is compatible with Intel fortran, but probably some more environment tweaks needed to work on Windows runners)

**Comment by wpbonelli** [comment]
possibly relevant: https://groups.google.com/g/comp.lang.fortran/c/Jna-QAHCOpk

**Comment by scharlton2** [comment]
@sanguinariojoe

* Another alternative is to use the ninja generator: `-G Ninja` or `-G Ninja Multi-Config` on windows.  I believe the reason cmake doesn't work under windows when cached is that the windows registry is not cached (which is difficult to do).

**Comment by sanguinariojoe** [comment]
The ninja trick seemed to work fine. Now it is using intel compiler for everything, but I suppose that is not really a problem
