### ISSUE TITLE
The Linux subsystem is broken after using this action

### ISSUE THREAD

**Issue by sanguinariojoe** [modflowpy/install-intelfortran-action#11]
Before the action usage you can safely run bash shell:

https://github.com/sanguinariojoe/MoorDyn/actions/runs/3302812370/jobs/5450026617#step:3:6

But after you are getting an error (`Windows Subsystem for Linux has no installed distributions.`):

https://github.com/sanguinariojoe/MoorDyn/actions/runs/3302812370/jobs/5450026617#step:11:4

This did not happened before https://github.com/modflowpy/install-intelfortran-action/pull/9 (see https://github.com/sanguinariojoe/MoorDyn/actions/runs/3273534330/jobs/5385863752)

**Comment by wpbonelli** [comment]
Thanks @sanguinariojoe, this was caused by [path manipulation](https://github.com/modflowpy/install-intelfortran-action/pull/12/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6L77) introduced in #9 to make sure cache contents are unzipped with Windows' default `tar`. This caused `C:\Windows\System32\bash.exe` to be used in subsequent steps instead of the default `C:\Program Files\Git\usr\bin\bash.EXE`. #12 reverts this in favor of temporarily hiding GNU `tar`.

**Comment by wpbonelli** [comment]
Passing test run [here](https://github.com/w-bonelli/MoorDyn/actions/runs/3304570836/jobs/5454090791), will update `modflowpy/install-intelfortran-action@v1` shortly

**Comment by wpbonelli** [comment]
`modflowpy/install-intelfortran-action@v1` has this update now but #10 is [still unresolved](https://github.com/w-bonelli/MoorDyn/actions/runs/3304672383/jobs/5454255649#step:10:51)
